### ISSUE TITLE
RKI

### ISSUE THREAD

**Issue by SeaLife** [covid19-eu-zh/covid19-eu-data#3]
Hey, they probably changed the RKI page again, pandas seems to fail to read the page properly..:

```
Traceback (most recent call last):
  File "covid19-eu-data/scripts/download_de.py", line 84, in <module>
    cov_de.workflow()
  File "covid19-eu-data\scripts\utils.py", line 100, in workflow
    self.extract_table()
  File "covid19-eu-data/scripts/download_de.py", line 42, in extract_table
    self.df = req_dfs[0][["Bundesland", "Fälle", "Todesfälle"]]
  File "lib\site-packages\pandas\core\frame.py", line 2806, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "lib\site-packages\pandas\core\indexing.py", line 1551, in _get_listlike_indexer
    self._validate_read_indexer(
  File "lib\site-packages\pandas\core\indexing.py", line 1645, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['Todesfälle', 'Fälle'] not in index"

Process finished with exit code 1
```

**Comment by emptymalei** [comment]
Fixed
